export const DEFAULT_LOCALE = 'en-US'
export const EN_LOCALE = 'en-US'
export const RU_LOCALE = 'ru-RU'
export const APP_CONFIG_FILE_NAME = 'app_config.json'
export const PATH_TO_LOCALES = 'app/config/locales/'
export const PATH_TO_APP_CONFIG = 'app/config/'
