"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PATH_TO_JSON_DB = exports.PATH_TO_APP_CONFIG = exports.PATH_TO_LOCALES = exports.APP_CONFIG_FILE_NAME = exports.RU_WORDS_FILE = exports.EN_WORDS_FILE = exports.RU_LOCALE = exports.EN_LOCALE = exports.DEFAULT_LOCALE = exports.BAD_STRING = exports.SORTING_MANUAL_EJS_PATH = exports.OPEN_FILE_EJS_PATH = exports.PARSER_LOG_EJS_PATH = exports.PARSER_CSV_EJS_PATH = exports.APP_ENTER_INDEX_EJS_PATH = exports.MAIN_SMAII_ICON_NAME = exports.MAIN_BIG_ICON_NAME = exports.MAIN_ICON_PATH = exports.APP_NAME = exports.APP_GITHUB = void 0;
exports.APP_GITHUB = 'https://github.com/luftkluft/dataviewer';
exports.APP_NAME = 'DataViewer';
exports.MAIN_ICON_PATH = '/app/public/icons/';
exports.MAIN_BIG_ICON_NAME = 'app-256x256.png';
exports.MAIN_SMAII_ICON_NAME = 'app-32x32.ico';
exports.APP_ENTER_INDEX_EJS_PATH = '/app/views/index.ejs';
exports.PARSER_CSV_EJS_PATH = '/app/views/parser_csv/parser_csv.ejs';
exports.PARSER_LOG_EJS_PATH = '/app/views/parser_log/parser_log.ejs';
exports.OPEN_FILE_EJS_PATH = '/app/views/open_file/open_file.ejs';
exports.SORTING_MANUAL_EJS_PATH = '/app/views/sorting_manual/sorting_manual.ejs';
exports.BAD_STRING = '#####';
exports.DEFAULT_LOCALE = 'en-US';
exports.EN_LOCALE = 'en-US';
exports.RU_LOCALE = 'ru-RU';
exports.EN_WORDS_FILE = 'en.json';
exports.RU_WORDS_FILE = 'ru.json';
exports.APP_CONFIG_FILE_NAME = 'app_config.json';
exports.PATH_TO_LOCALES = '/app/config/locales/';
exports.PATH_TO_APP_CONFIG = '/app/config/';
exports.PATH_TO_JSON_DB = '/app/db/';
//# sourceMappingURL=constants.js.map